
server:
  port: 8085
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/raulTSantos/basic-microservices-spring
          username: myusername
          password: mypassword
          search-paths: config-data
  application:
    name: config-service